# Generated by Django 6.0.7 on 2026-07-28 11:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BehavioralRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('label', models.CharField(max_length=50)),
                ('numeric_value', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['numeric_value'],
            },
        ),
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BehaviorIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('core_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='behavior.corevalue')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'core_value')},
            },
        ),
        migrations.CreateModel(
            name='BehavioralAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grading_period_type', models.CharField(default='Quarter', max_length=20)),
                ('quarter', models.PositiveIntegerField(blank=True, null=True)),
                ('semester', models.PositiveIntegerField(blank=True, null=True)),
                ('numeric_score', models.DecimalField(decimal_places=2, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('assessment_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavioral_assessments', to='academics.academicyear')),
                ('assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessed_behavioral_records', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavioral_assessments', to='academics.enrollment')),
                ('rating', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='behavior.behavioralrating')),
                ('behavior_indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='behavior.behaviorindicator')),
                ('core_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='behavior.corevalue')),
            ],
            options={
                'ordering': ['-assessment_date', '-created_at'],
                'indexes': [models.Index(fields=['academic_year', 'grading_period_type', 'quarter', 'semester'], name='behavior_be_academi_4c9726_idx')],
                'unique_together': {('enrollment', 'academic_year', 'core_value', 'behavior_indicator', 'grading_period_type', 'quarter', 'semester')},
            },
        ),
    ]
