# Generated by Django 6.0.7 on 2026-07-28 16:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('behavior', '0002_make_behavior_rating_optional_numeric'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='behavioralrating',
            options={'ordering': ['code']},
        ),
        migrations.AlterField(
            model_name='behavioralassessment',
            name='numeric_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
