# Generated by Django 6.0.7 on 2026-07-28 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'CREATE'), ('UPDATE', 'UPDATE'), ('DELETE', 'DELETE'), ('LOGIN', 'LOGIN'), ('LOGOUT', 'LOGOUT'), ('VIEW_SENSITIVE_RECORD', 'VIEW_SENSITIVE_RECORD'), ('EXPORT_REPORT', 'EXPORT_REPORT'), ('PREDICTION_GENERATED', 'PREDICTION_GENERATED'), ('INTERVENTION_CREATED', 'INTERVENTION_CREATED')], max_length=30)),
                ('module', models.CharField(max_length=100)),
                ('object_type', models.CharField(blank=True, default='', max_length=100)),
                ('object_id', models.CharField(blank=True, default='', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='audit_audit_user_id_e8be02_idx'), models.Index(fields=['module', 'action'], name='audit_audit_module_365bd8_idx')],
            },
        ),
    ]
