# Generated by Django 6.0.7 on 2026-07-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'CREATE'), ('UPDATE', 'UPDATE'), ('DELETE', 'DELETE'), ('LOGIN_SUCCESS', 'LOGIN_SUCCESS'), ('LOGIN_FAILED', 'LOGIN_FAILED'), ('LOGOUT', 'LOGOUT'), ('ACCOUNT_ACTIVATED', 'ACCOUNT_ACTIVATED'), ('ACCOUNT_DEACTIVATED', 'ACCOUNT_DEACTIVATED'), ('PASSWORD_CHANGED', 'PASSWORD_CHANGED'), ('USER_CREATED', 'USER_CREATED'), ('VIEW_SENSITIVE_RECORD', 'VIEW_SENSITIVE_RECORD'), ('EXPORT_REPORT', 'EXPORT_REPORT'), ('PREDICTION_GENERATED', 'PREDICTION_GENERATED'), ('INTERVENTION_CREATED', 'INTERVENTION_CREATED')], max_length=30),
        ),
    ]
